<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-12-30 03:07

$extensionPath = t3lib_extMgm::extPath('mail2news');
return array(
	'tx_mail2news_getmail' => $extensionPath . 'class.tx_mail2news_getmail.php',
	'tx_mail2news_imap' => $extensionPath . 'class.tx_mail2news_imap.php',
	'tx_mail2news_scheduler_start' => $extensionPath . 'class.tx_mail2news_scheduler_start.php',
	'tx_mail2news_t3blog' => $extensionPath . 'class.tx_mail2news_t3blog.php',
	'tx_mail2news_ttnews' => $extensionPath . 'class.tx_mail2news_ttnews.php',
	'tx_mail2news_getmailtest' => $extensionPath . 'Tests/Unit/class.tx_mail2news_getmailTest.php',
	'tx_mail2news_ttnewstest' => $extensionPath . 'Tests/Unit/class.tx_mail2news_ttnewsTest.php',
	'tx_mail2news_phpunittypo3db' => $extensionPath . 'Tests/Unit/Fixtures/class.tx_mail2news_phpunittypo3db.php',
);
?>